# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatbot.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchatbot.proto\x12\x07\x63hatbot\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0bUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"3\n\x0eMessageRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"\x0c\n\nGetRequest\"\x1f\n\x0bListRequest\x12\x10\n\x08wildcard\x18\x01 \x01(\t\"\x1f\n\x0c\x43hatbotReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb8\x03\n\x07\x43hatBot\x12\x38\n\x08SayHello\x12\x15.chatbot.HelloRequest\x1a\x13.chatbot.HelloReply\"\x00\x12<\n\x0b\x63reate_user\x12\x14.chatbot.UserRequest\x1a\x15.chatbot.ChatbotReply\"\x00\x12@\n\x0csend_message\x12\x17.chatbot.MessageRequest\x1a\x15.chatbot.ChatbotReply\"\x00\x12;\n\x0bget_message\x12\x13.chatbot.GetRequest\x1a\x15.chatbot.ChatbotReply\"\x00\x12;\n\nlist_users\x12\x14.chatbot.ListRequest\x1a\x15.chatbot.ChatbotReply\"\x00\x12<\n\x0b\x64\x65lete_user\x12\x14.chatbot.UserRequest\x1a\x15.chatbot.ChatbotReply\"\x00\x12;\n\nlogin_user\x12\x14.chatbot.UserRequest\x1a\x15.chatbot.ChatbotReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatbot_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=26
  _HELLOREQUEST._serialized_end=54
  _HELLOREPLY._serialized_start=56
  _HELLOREPLY._serialized_end=85
  _USERREQUEST._serialized_start=87
  _USERREQUEST._serialized_end=118
  _MESSAGEREQUEST._serialized_start=120
  _MESSAGEREQUEST._serialized_end=171
  _GETREQUEST._serialized_start=173
  _GETREQUEST._serialized_end=185
  _LISTREQUEST._serialized_start=187
  _LISTREQUEST._serialized_end=218
  _CHATBOTREPLY._serialized_start=220
  _CHATBOTREPLY._serialized_end=251
  _CHATBOT._serialized_start=254
  _CHATBOT._serialized_end=694
# @@protoc_insertion_point(module_scope)
