# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pong_pb2 as pong__pb2


class PongServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.paddle_stream = channel.unary_stream(
                '/pong.PongServer/paddle_stream',
                request_serializer=pong__pb2.PaddleRequest.SerializeToString,
                response_deserializer=pong__pb2.PaddlePosition.FromString,
                )
        self.move = channel.unary_unary(
                '/pong.PongServer/move',
                request_serializer=pong__pb2.PaddleMovement.SerializeToString,
                response_deserializer=pong__pb2.Empty.FromString,
                )
        self.initialize_game = channel.unary_stream(
                '/pong.PongServer/initialize_game',
                request_serializer=pong__pb2.Empty.SerializeToString,
                response_deserializer=pong__pb2.GameReady.FromString,
                )


class PongServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def paddle_stream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def move(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def initialize_game(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PongServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'paddle_stream': grpc.unary_stream_rpc_method_handler(
                    servicer.paddle_stream,
                    request_deserializer=pong__pb2.PaddleRequest.FromString,
                    response_serializer=pong__pb2.PaddlePosition.SerializeToString,
            ),
            'move': grpc.unary_unary_rpc_method_handler(
                    servicer.move,
                    request_deserializer=pong__pb2.PaddleMovement.FromString,
                    response_serializer=pong__pb2.Empty.SerializeToString,
            ),
            'initialize_game': grpc.unary_stream_rpc_method_handler(
                    servicer.initialize_game,
                    request_deserializer=pong__pb2.Empty.FromString,
                    response_serializer=pong__pb2.GameReady.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pong.PongServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PongServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def paddle_stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/pong.PongServer/paddle_stream',
            pong__pb2.PaddleRequest.SerializeToString,
            pong__pb2.PaddlePosition.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pong.PongServer/move',
            pong__pb2.PaddleMovement.SerializeToString,
            pong__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def initialize_game(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/pong.PongServer/initialize_game',
            pong__pb2.Empty.SerializeToString,
            pong__pb2.GameReady.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
