# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pong.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npong.proto\x12\x04grpc\"\x07\n\x05\x45mpty\"\x1b\n\x06Player\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\")\n\x05Score\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x05\"I\n\x0ePaddlePosition\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\x0e\n\x06yspeed\x18\x04 \x01(\x02\"D\n\x0c\x42\x61llPosition\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x0e\n\x06xspeed\x18\x03 \x01(\x02\x12\x0e\n\x06yspeed\x18\x04 \x01(\x02\x32\xe3\x01\n\nPongServer\x12\x36\n\nBallStream\x12\x12.grpc.BallPosition\x1a\x12.grpc.BallPosition0\x01\x12<\n\x0cPaddleStream\x12\x14.grpc.PaddlePosition\x1a\x14.grpc.PaddlePosition0\x01\x12.\n\x11initialize_player\x12\x0b.grpc.Empty\x1a\x0c.grpc.Player\x12/\n\x0cupdate_score\x12\x12.grpc.BallPosition\x1a\x0b.grpc.Scoreb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pong_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=20
  _EMPTY._serialized_end=27
  _PLAYER._serialized_start=29
  _PLAYER._serialized_end=56
  _SCORE._serialized_start=58
  _SCORE._serialized_end=99
  _PADDLEPOSITION._serialized_start=101
  _PADDLEPOSITION._serialized_end=174
  _BALLPOSITION._serialized_start=176
  _BALLPOSITION._serialized_end=244
  _PONGSERVER._serialized_start=247
  _PONGSERVER._serialized_end=474
# @@protoc_insertion_point(module_scope)
